// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1--rc1
// source: proto/votacaoservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VotacaoClient is the client API for Votacao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VotacaoClient interface {
	BuscarPorId(ctx context.Context, in *BuscarRequest, opts ...grpc.CallOption) (*BuscarResponse, error)
}

type votacaoClient struct {
	cc grpc.ClientConnInterface
}

func NewVotacaoClient(cc grpc.ClientConnInterface) VotacaoClient {
	return &votacaoClient{cc}
}

func (c *votacaoClient) BuscarPorId(ctx context.Context, in *BuscarRequest, opts ...grpc.CallOption) (*BuscarResponse, error) {
	out := new(BuscarResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Votacao/BuscarPorId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VotacaoServer is the server API for Votacao service.
// All implementations must embed UnimplementedVotacaoServer
// for forward compatibility
type VotacaoServer interface {
	BuscarPorId(context.Context, *BuscarRequest) (*BuscarResponse, error)
	mustEmbedUnimplementedVotacaoServer()
}

// UnimplementedVotacaoServer must be embedded to have forward compatible implementations.
type UnimplementedVotacaoServer struct {
}

func (UnimplementedVotacaoServer) BuscarPorId(context.Context, *BuscarRequest) (*BuscarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuscarPorId not implemented")
}
func (UnimplementedVotacaoServer) mustEmbedUnimplementedVotacaoServer() {}

// UnsafeVotacaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VotacaoServer will
// result in compilation errors.
type UnsafeVotacaoServer interface {
	mustEmbedUnimplementedVotacaoServer()
}

func RegisterVotacaoServer(s grpc.ServiceRegistrar, srv VotacaoServer) {
	s.RegisterService(&Votacao_ServiceDesc, srv)
}

func _Votacao_BuscarPorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuscarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VotacaoServer).BuscarPorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Votacao/BuscarPorId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VotacaoServer).BuscarPorId(ctx, req.(*BuscarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Votacao_ServiceDesc is the grpc.ServiceDesc for Votacao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Votacao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Votacao",
	HandlerType: (*VotacaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuscarPorId",
			Handler:    _Votacao_BuscarPorId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/votacaoservice.proto",
}
