// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1--rc1
// source: proto/votacaoservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestVazio) Reset() {
	*x = RequestVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_votacaoservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVazio) ProtoMessage() {}

func (x *RequestVazio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votacaoservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVazio.ProtoReflect.Descriptor instead.
func (*RequestVazio) Descriptor() ([]byte, []int) {
	return file_proto_votacaoservice_proto_rawDescGZIP(), []int{0}
}

type ResponseVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseVazio) Reset() {
	*x = ResponseVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_votacaoservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVazio) ProtoMessage() {}

func (x *ResponseVazio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votacaoservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVazio.ProtoReflect.Descriptor instead.
func (*ResponseVazio) Descriptor() ([]byte, []int) {
	return file_proto_votacaoservice_proto_rawDescGZIP(), []int{1}
}

type BuscarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BuscarRequest) Reset() {
	*x = BuscarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_votacaoservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarRequest) ProtoMessage() {}

func (x *BuscarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votacaoservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarRequest.ProtoReflect.Descriptor instead.
func (*BuscarRequest) Descriptor() ([]byte, []int) {
	return file_proto_votacaoservice_proto_rawDescGZIP(), []int{2}
}

func (x *BuscarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuscarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *BuscarResponse) Reset() {
	*x = BuscarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_votacaoservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarResponse) ProtoMessage() {}

func (x *BuscarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_votacaoservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarResponse.ProtoReflect.Descriptor instead.
func (*BuscarResponse) Descriptor() ([]byte, []int) {
	return file_proto_votacaoservice_proto_rawDescGZIP(), []int{3}
}

func (x *BuscarResponse) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

var File_proto_votacaoservice_proto protoreflect.FileDescriptor

var file_proto_votacaoservice_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x6f, 0x74, 0x61, 0x63, 0x61, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x22, 0x1f, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x63, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x42, 0x75, 0x73, 0x63,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x32, 0x4d,
	0x0a, 0x07, 0x56, 0x6f, 0x74, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x42, 0x0a, 0x0b, 0x42, 0x75, 0x73,
	0x63, 0x61, 0x72, 0x50, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x75, 0x73,
	0x63, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a,
	0x14, 0x44, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x54, 0x65, 0x63, 0x6e, 0x69, 0x63, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_votacaoservice_proto_rawDescOnce sync.Once
	file_proto_votacaoservice_proto_rawDescData = file_proto_votacaoservice_proto_rawDesc
)

func file_proto_votacaoservice_proto_rawDescGZIP() []byte {
	file_proto_votacaoservice_proto_rawDescOnce.Do(func() {
		file_proto_votacaoservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_votacaoservice_proto_rawDescData)
	})
	return file_proto_votacaoservice_proto_rawDescData
}

var file_proto_votacaoservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_votacaoservice_proto_goTypes = []interface{}{
	(*RequestVazio)(nil),   // 0: protobuf.RequestVazio
	(*ResponseVazio)(nil),  // 1: protobuf.ResponseVazio
	(*BuscarRequest)(nil),  // 2: protobuf.BuscarRequest
	(*BuscarResponse)(nil), // 3: protobuf.BuscarResponse
}
var file_proto_votacaoservice_proto_depIdxs = []int32{
	2, // 0: protobuf.Votacao.BuscarPorId:input_type -> protobuf.BuscarRequest
	3, // 1: protobuf.Votacao.BuscarPorId:output_type -> protobuf.BuscarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_votacaoservice_proto_init() }
func file_proto_votacaoservice_proto_init() {
	if File_proto_votacaoservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_votacaoservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_votacaoservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_votacaoservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_votacaoservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_votacaoservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_votacaoservice_proto_goTypes,
		DependencyIndexes: file_proto_votacaoservice_proto_depIdxs,
		MessageInfos:      file_proto_votacaoservice_proto_msgTypes,
	}.Build()
	File_proto_votacaoservice_proto = out.File
	file_proto_votacaoservice_proto_rawDesc = nil
	file_proto_votacaoservice_proto_goTypes = nil
	file_proto_votacaoservice_proto_depIdxs = nil
}
